//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vulcan.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vulcan.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;RSAParameters xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://ww
        ///w.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///  &lt;Modulus&gt;kd6UF8pKoS+kNbHmIEz/InQ1cKrDRUzbIHI+FOKk9T5GDEVMNlRG7UjXxnDq3O+dj5OXX
        ///oXu73z0zeNkkhYvA0T/mxViYKNdXfoA4Wlyz/HZ/lxeUNUsvAgOlQ3L4weC0knpXiXdf2S0Xz+R7sfmG
        ///jmvpIJbYmpFvamQTHSV6M0oHwFHoYNrTYauqUnZ5jy6eBIAabRFr05IgCF/vUb8T8RPnuq+dK7IH/Qh1
        ///Uxiucm5Fotv8qD8bo98PV8ifXwIIY8byPsoOQRS78ZGyS6oHD9/PefVV9X0Kt3thbVcsVxTQln4idf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PublicRSAKey {
            get {
                return ResourceManager.GetString("PublicRSAKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TskSched {
            get {
                object obj = ResourceManager.GetObject("TskSched", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZipLib {
            get {
                object obj = ResourceManager.GetObject("ZipLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
